### ISSUE TITLE
tags not working

### ISSUE THREAD

**Issue by Pakillo** [ecoinfAEET/ecoinfAEET.github.io#11]
if you click on any tag from a post, you get a 'server not found' error. 
there seems to be a missing /
this is address it's trying to see: http://ecoinfaeet.github.iotags/#reproducibilidad

**Comment by ajpelu** [comment]
@Pakillo @ibartomeus 
I fixed this error. Tag links work fine. Try it, please!!

**Comment by Pakillo** [comment]
Perfecto! Muchas gracias @ajpelu !
